// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/controller"
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/mapper"
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/middleware"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/document_recipient_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/document_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/folder_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/system_injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/system_role_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tag_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_tag_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_signer_role_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tenant_member_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tenant_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/user_access_history_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/user_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_member_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_repo"
	"github.com/doc-assembly/doc-engine/internal/core/service"
	"github.com/doc-assembly/doc-engine/internal/infra"
	"github.com/doc-assembly/doc-engine/internal/infra/config"
	"github.com/doc-assembly/doc-engine/internal/infra/server"
)

// Injectors from wire.go:

// InitializeApp creates the application with all dependencies wired.
func InitializeApp() (*infra.Initializer, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	databaseConfig := infra.ProvideDatabaseConfig(configConfig)
	pool, err := infra.ProvideDBPool(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := userrepo.New(pool)
	systemRoleRepository := systemrolerepo.New(pool)
	workspaceRepository := workspacerepo.New(pool)
	workspaceMemberRepository := workspacememberrepo.New(pool)
	tenantMemberRepository := tenantmemberrepo.New(pool)
	provider := middleware.NewProvider(userRepository, systemRoleRepository, workspaceRepository, workspaceMemberRepository, tenantMemberRepository)
	tenantRepository := tenantrepo.New(pool)
	userAccessHistoryRepository := useraccesshistoryrepo.New(pool)
	workspaceUseCase := service.NewWorkspaceService(workspaceRepository, tenantRepository, workspaceMemberRepository, userAccessHistoryRepository)
	folderRepository := folderrepo.New(pool)
	folderUseCase := service.NewFolderService(folderRepository)
	tagRepository := tagrepo.New(pool)
	tagUseCase := service.NewTagService(tagRepository)
	workspaceMemberUseCase := service.NewWorkspaceMemberService(workspaceMemberRepository, userRepository)
	workspaceInjectableRepository := workspaceinjectablerepo.New(pool)
	workspaceInjectableUseCase := service.NewWorkspaceInjectableService(workspaceInjectableRepository)
	injectableMapper := mapper.NewInjectableMapper()
	workspaceController := controller.NewWorkspaceController(workspaceUseCase, folderUseCase, tagUseCase, workspaceMemberUseCase, workspaceInjectableUseCase, injectableMapper)
	injectableRepository := injectablerepo.New(pool)
	systemInjectableRepository := systeminjectablerepo.New(pool)
	injectorI18nConfig, err := config.LoadInjectorI18n()
	if err != nil {
		return nil, err
	}
	mapperRegistry := infra.ProvideMapperRegistry()
	initDeps := infra.ProvideExtensionDeps()
	injectorRegistry := infra.ProvideInjectorRegistry(injectorI18nConfig, mapperRegistry, initDeps)
	injectableUseCase := service.NewInjectableService(injectableRepository, systemInjectableRepository, injectorRegistry)
	contentInjectableController := controller.NewContentInjectableController(injectableUseCase, injectableMapper)
	templateRepository := templaterepo.New(pool)
	templateVersionRepository := templateversionrepo.New(pool)
	templateTagRepository := templatetagrepo.New(pool)
	templateUseCase := service.NewTemplateService(templateRepository, templateVersionRepository, templateTagRepository)
	templateVersionMapper := mapper.NewTemplateVersionMapper(injectableMapper)
	tagMapper := mapper.NewTagMapper()
	folderMapper := mapper.NewFolderMapper()
	templateMapper := mapper.NewTemplateMapper(templateVersionMapper, tagMapper, folderMapper)
	templateVersionInjectableRepository := templateversioninjectablerepo.New(pool)
	templateVersionSignerRoleRepository := templateversionsignerrolerepo.New(pool)
	contentValidator := infra.ProvideContentValidator(injectableRepository)
	templateVersionUseCase := service.NewTemplateVersionService(templateVersionRepository, templateVersionInjectableRepository, templateVersionSignerRoleRepository, templateRepository, templateTagRepository, contentValidator, workspaceRepository)
	pdfRenderer, err := infra.ProvidePDFRenderer()
	if err != nil {
		return nil, err
	}
	renderController := controller.NewRenderController(templateVersionUseCase, pdfRenderer)
	templateVersionController := controller.NewTemplateVersionController(templateVersionUseCase, templateVersionMapper, templateMapper, renderController)
	contentTemplateController := controller.NewContentTemplateController(templateUseCase, templateMapper, templateVersionController)
	tenantUseCase := service.NewTenantService(tenantRepository, workspaceRepository, tenantMemberRepository, systemRoleRepository, userAccessHistoryRepository)
	systemRoleUseCase := service.NewSystemRoleService(systemRoleRepository, userRepository)
	systemInjectableUseCase := service.NewSystemInjectableService(systemInjectableRepository, injectorRegistry)
	adminController := controller.NewAdminController(tenantUseCase, systemRoleUseCase, systemInjectableUseCase)
	userAccessHistoryUseCase := service.NewUserAccessHistoryService(userAccessHistoryRepository)
	meController := controller.NewMeController(tenantUseCase, tenantMemberRepository, workspaceMemberRepository, userAccessHistoryUseCase)
	tenantMemberUseCase := service.NewTenantMemberService(tenantMemberRepository, userRepository)
	tenantController := controller.NewTenantController(tenantUseCase, workspaceUseCase, tenantMemberUseCase)
	documentRepository := documentrepo.New(pool)
	documentRecipientRepository := documentrecipientrepo.New(pool)
	injectableResolverService := infra.ProvideInjectableResolver(injectorRegistry)
	documentGenerator := infra.ProvideDocumentGenerator(templateRepository, templateVersionRepository, documentRepository, documentRecipientRepository, injectableUseCase, mapperRegistry, injectableResolverService)
	internalDocumentUseCase := infra.ProvideInternalDocumentService(documentGenerator)
	internalDocumentController := controller.NewInternalDocumentController(internalDocumentUseCase)
	httpServer := server.NewHTTPServer(configConfig, provider, workspaceController, contentInjectableController, contentTemplateController, adminController, meController, tenantController, internalDocumentController)
	initializer := infra.NewInitializer(httpServer, pool)
	return initializer, nil
}
