// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/controller"
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/mapper"
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/middleware"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/document_event_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/document_recipient_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/document_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/document_type_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/folder_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/system_injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/system_role_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tag_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_tag_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_signer_role_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tenant_member_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tenant_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/user_access_history_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/user_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_member_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_repo"
	"github.com/doc-assembly/doc-engine/internal/core/service/access"
	"github.com/doc-assembly/doc-engine/internal/core/service/catalog"
	"github.com/doc-assembly/doc-engine/internal/core/service/document"
	"github.com/doc-assembly/doc-engine/internal/core/service/injectable"
	"github.com/doc-assembly/doc-engine/internal/core/service/organization"
	"github.com/doc-assembly/doc-engine/internal/core/service/template"
	"github.com/doc-assembly/doc-engine/internal/infra"
	"github.com/doc-assembly/doc-engine/internal/infra/config"
	"github.com/doc-assembly/doc-engine/internal/infra/server"
)

// Injectors from wire.go:

// InitializeApp creates the application with all dependencies wired.
func InitializeApp() (*infra.Initializer, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	pool, err := infra.ProvideDBPool(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := userrepo.New(pool)
	systemRoleRepository := systemrolerepo.New(pool)
	workspaceRepository := workspacerepo.New(pool)
	workspaceMemberRepository := workspacememberrepo.New(pool)
	tenantMemberRepository := tenantmemberrepo.New(pool)
	provider := middleware.NewProvider(userRepository, systemRoleRepository, workspaceRepository, workspaceMemberRepository, tenantMemberRepository)
	tenantRepository := tenantrepo.New(pool)
	userAccessHistoryRepository := useraccesshistoryrepo.New(pool)
	workspaceUseCase := organization.NewWorkspaceService(workspaceRepository, tenantRepository, workspaceMemberRepository, userAccessHistoryRepository)
	folderRepository := folderrepo.New(pool)
	folderUseCase := catalog.NewFolderService(folderRepository)
	tagRepository := tagrepo.New(pool)
	tagUseCase := catalog.NewTagService(tagRepository)
	workspaceMemberUseCase := organization.NewWorkspaceMemberService(workspaceMemberRepository, userRepository)
	workspaceInjectableRepository := workspaceinjectablerepo.New(pool)
	workspaceInjectableUseCase := injectable.NewWorkspaceInjectableService(workspaceInjectableRepository)
	injectableMapper := mapper.NewInjectableMapper()
	workspaceController := controller.NewWorkspaceController(workspaceUseCase, folderUseCase, tagUseCase, workspaceMemberUseCase, workspaceInjectableUseCase, injectableMapper)
	injectableRepository := injectablerepo.New(pool)
	systemInjectableRepository := systeminjectablerepo.New(pool)
	injectorI18nConfig, err := config.LoadInjectorI18n()
	if err != nil {
		return nil, err
	}
	mapperRegistry := infra.ProvideMapperRegistry()
	initDeps := infra.ProvideExtensionDeps()
	injectorRegistry := infra.ProvideInjectorRegistry(injectorI18nConfig, mapperRegistry, initDeps)
	workspaceInjectableProvider := infra.ProvideWorkspaceInjectableProvider()
	injectableUseCase := injectable.NewInjectableService(injectableRepository, systemInjectableRepository, injectorRegistry, workspaceRepository, tenantRepository, workspaceInjectableProvider)
	contentInjectableController := controller.NewContentInjectableController(injectableUseCase, injectableMapper)
	templateRepository := templaterepo.New(pool)
	templateVersionRepository := templateversionrepo.New(pool)
	templateTagRepository := templatetagrepo.New(pool)
	templateUseCase := template.NewTemplateService(templateRepository, templateVersionRepository, templateTagRepository)
	templateVersionMapper := mapper.NewTemplateVersionMapper(injectableMapper)
	tagMapper := mapper.NewTagMapper()
	folderMapper := mapper.NewFolderMapper()
	templateMapper := mapper.NewTemplateMapper(templateVersionMapper, tagMapper, folderMapper)
	templateVersionInjectableRepository := templateversioninjectablerepo.New(pool)
	templateVersionSignerRoleRepository := templateversionsignerrolerepo.New(pool)
	contentValidator := infra.ProvideContentValidator(injectableUseCase)
	templateVersionUseCase := template.NewTemplateVersionService(templateVersionRepository, templateVersionInjectableRepository, templateVersionSignerRoleRepository, templateRepository, templateTagRepository, contentValidator, workspaceRepository)
	typstConfig := infra.ProvideTypstConfig(configConfig)
	pdfRenderer, err := infra.ProvidePDFRenderer(typstConfig)
	if err != nil {
		return nil, err
	}
	renderController := controller.NewRenderController(templateVersionUseCase, pdfRenderer)
	templateVersionController := controller.NewTemplateVersionController(templateVersionUseCase, templateVersionMapper, templateMapper, renderController)
	contentTemplateController := controller.NewContentTemplateController(templateUseCase, templateMapper, templateVersionController)
	tenantUseCase := organization.NewTenantService(tenantRepository, workspaceRepository, tenantMemberRepository, systemRoleRepository, userAccessHistoryRepository)
	systemRoleUseCase := access.NewSystemRoleService(systemRoleRepository, userRepository)
	systemInjectableUseCase := injectable.NewSystemInjectableService(systemInjectableRepository, injectorRegistry)
	adminController := controller.NewAdminController(tenantUseCase, systemRoleUseCase, systemInjectableUseCase)
	userAccessHistoryUseCase := access.NewUserAccessHistoryService(userAccessHistoryRepository)
	meController := controller.NewMeController(tenantUseCase, tenantMemberRepository, workspaceMemberRepository, userAccessHistoryUseCase)
	tenantMemberUseCase := organization.NewTenantMemberService(tenantMemberRepository, userRepository)
	tenantController := controller.NewTenantController(tenantUseCase, workspaceUseCase, tenantMemberUseCase)
	documentTypeRepository := documenttyperepo.New(pool)
	documentTypeUseCase := catalog.NewDocumentTypeService(documentTypeRepository, templateRepository)
	documentTypeController := controller.NewDocumentTypeController(documentTypeUseCase, templateUseCase, templateMapper)
	documentRepository := documentrepo.New(pool)
	documentRecipientRepository := documentrecipientrepo.New(pool)
	signingConfig := infra.ProvideSigningConfig(configConfig)
	signingProvider, err := infra.ProvideSigningProvider(signingConfig)
	if err != nil {
		return nil, err
	}
	storageAdapter, err := infra.ProvideStorageAdapter(configConfig)
	if err != nil {
		return nil, err
	}
	documentEventRepository := documenteventrepo.New(pool)
	eventEmitter := document.NewEventEmitter(documentEventRepository)
	notificationProvider := infra.ProvideNotificationProvider(configConfig)
	notificationService := document.NewNotificationService(notificationProvider, documentRecipientRepository, documentRepository)
	schedulerConfig := infra.ProvideSchedulerConfig(configConfig)
	documentUseCase := infra.ProvideDocumentService(documentRepository, documentRecipientRepository, templateVersionRepository, templateVersionSignerRoleRepository, pdfRenderer, signingProvider, storageAdapter, eventEmitter, notificationService, schedulerConfig)
	documentController := controller.NewDocumentController(documentUseCase, eventEmitter)
	v, err := infra.ProvideWebhookHandlers(signingConfig)
	if err != nil {
		return nil, err
	}
	webhookController := controller.NewWebhookController(documentUseCase, v)
	injectableResolverService := infra.ProvideInjectableResolver(injectorRegistry)
	documentGenerator := infra.ProvideDocumentGenerator(templateRepository, templateVersionRepository, documentRepository, documentRecipientRepository, injectableUseCase, mapperRegistry, injectableResolverService)
	internalDocumentUseCase := infra.ProvideInternalDocumentService(documentGenerator, documentRepository, documentRecipientRepository, pdfRenderer, signingProvider)
	internalDocumentController := controller.NewInternalDocumentController(internalDocumentUseCase)
	renderAuthenticator := infra.ProvideRenderAuthenticator()
	httpServer := server.NewHTTPServer(configConfig, provider, workspaceController, contentInjectableController, contentTemplateController, adminController, meController, tenantController, documentTypeController, documentController, webhookController, internalDocumentController, renderAuthenticator)
	scheduler := infra.ProvideScheduler(schedulerConfig, documentUseCase)
	initializer := infra.NewInitializer(httpServer, pool, scheduler)
	return initializer, nil
}
