// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/controller"
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/mapper"
	"github.com/doc-assembly/doc-engine/internal/adapters/primary/http/middleware"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/folder_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/system_role_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tag_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_tag_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_injectable_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/template_version_signer_role_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tenant_member_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/tenant_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/user_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_member_repo"
	"github.com/doc-assembly/doc-engine/internal/adapters/secondary/database/postgres/workspace_repo"
	"github.com/doc-assembly/doc-engine/internal/core/service"
	"github.com/doc-assembly/doc-engine/internal/infra"
	"github.com/doc-assembly/doc-engine/internal/infra/config"
	"github.com/doc-assembly/doc-engine/internal/infra/server"
)

// Injectors from wire.go:

// InitializeApp creates the application with all dependencies wired.
func InitializeApp() (*infra.Initializer, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	databaseConfig := infra.ProvideDatabaseConfig(configConfig)
	pool, err := infra.ProvideDBPool(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := userrepo.New(pool)
	systemRoleRepository := systemrolerepo.New(pool)
	workspaceRepository := workspacerepo.New(pool)
	workspaceMemberRepository := workspacememberrepo.New(pool)
	tenantMemberRepository := tenantmemberrepo.New(pool)
	provider := middleware.NewProvider(userRepository, systemRoleRepository, workspaceRepository, workspaceMemberRepository, tenantMemberRepository)
	tenantRepository := tenantrepo.New(pool)
	workspaceUseCase := service.NewWorkspaceService(workspaceRepository, tenantRepository, workspaceMemberRepository)
	folderRepository := folderrepo.New(pool)
	folderUseCase := service.NewFolderService(folderRepository)
	tagRepository := tagrepo.New(pool)
	tagUseCase := service.NewTagService(tagRepository)
	workspaceMemberUseCase := service.NewWorkspaceMemberService(workspaceMemberRepository, userRepository)
	workspaceController := controller.NewWorkspaceController(workspaceUseCase, folderUseCase, tagUseCase, workspaceMemberUseCase)
	injectableRepository := injectablerepo.New(pool)
	injectableUseCase := service.NewInjectableService(injectableRepository)
	injectableMapper := mapper.NewInjectableMapper()
	contentInjectableController := controller.NewContentInjectableController(injectableUseCase, injectableMapper)
	templateRepository := templaterepo.New(pool)
	templateVersionRepository := templateversionrepo.New(pool)
	templateTagRepository := templatetagrepo.New(pool)
	templateUseCase := service.NewTemplateService(templateRepository, templateVersionRepository, templateTagRepository)
	templateVersionMapper := mapper.NewTemplateVersionMapper(injectableMapper)
	tagMapper := mapper.NewTagMapper()
	folderMapper := mapper.NewFolderMapper()
	templateMapper := mapper.NewTemplateMapper(templateVersionMapper, tagMapper, folderMapper)
	templateVersionInjectableRepository := templateversioninjectablerepo.New(pool)
	templateVersionSignerRoleRepository := templateversionsignerrolerepo.New(pool)
	templateVersionUseCase := service.NewTemplateVersionService(templateVersionRepository, templateVersionInjectableRepository, templateVersionSignerRoleRepository, templateRepository)
	templateVersionController := controller.NewTemplateVersionController(templateVersionUseCase, templateVersionMapper)
	contentTemplateController := controller.NewContentTemplateController(templateUseCase, templateMapper, templateVersionController)
	tenantUseCase := service.NewTenantService(tenantRepository, workspaceRepository, tenantMemberRepository)
	systemRoleUseCase := service.NewSystemRoleService(systemRoleRepository, userRepository)
	adminController := controller.NewAdminController(tenantUseCase, workspaceUseCase, systemRoleUseCase)
	meController := controller.NewMeController(tenantUseCase)
	tenantMemberUseCase := service.NewTenantMemberService(tenantMemberRepository, userRepository)
	tenantController := controller.NewTenantController(tenantUseCase, workspaceUseCase, tenantMemberUseCase)
	httpServer := server.NewHTTPServer(configConfig, provider, workspaceController, contentInjectableController, contentTemplateController, adminController, meController, tenantController)
	initializer := infra.NewInitializer(httpServer, pool)
	return initializer, nil
}
