version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - revive
    - gosec
    - prealloc
    - nilerr
    - errorlint
    - exhaustive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
      - path: wire_gen\.go
        linters:
          - all
  settings:
    revive:
      rules:
        - name: var-naming
        - name: blank-imports
        - name: exported
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G104
    exhaustive:
      default-signifies-exhaustive: true

run:
  go: "1.25.1"
  timeout: 5m
  tests: true
