/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as EditorTestRouteImport } from './routes/editor-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace/$workspaceId'
import { Route as SystemTenantsRouteImport } from './routes/system/tenants'
import { Route as WorkspaceWorkspaceIdIndexRouteImport } from './routes/workspace/$workspaceId/index'

const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorTestRoute = EditorTestRouteImport.update({
  id: '/editor-test',
  path: '/editor-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemTenantsRoute = SystemTenantsRouteImport.update({
  id: '/system/tenants',
  path: '/system/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor-test': typeof EditorTestRoute
  '/select-tenant': typeof SelectTenantRoute
  '/system/tenants': typeof SystemTenantsRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor-test': typeof EditorTestRoute
  '/select-tenant': typeof SelectTenantRoute
  '/system/tenants': typeof SystemTenantsRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor-test': typeof EditorTestRoute
  '/select-tenant': typeof SelectTenantRoute
  '/system/tenants': typeof SystemTenantsRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor-test'
    | '/select-tenant'
    | '/system/tenants'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor-test'
    | '/select-tenant'
    | '/system/tenants'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/editor-test'
    | '/select-tenant'
    | '/system/tenants'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorTestRoute: typeof EditorTestRoute
  SelectTenantRoute: typeof SelectTenantRoute
  SystemTenantsRoute: typeof SystemTenantsRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor-test': {
      id: '/editor-test'
      path: '/editor-test'
      fullPath: '/editor-test'
      preLoaderRoute: typeof EditorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/tenants': {
      id: '/system/tenants'
      path: '/system/tenants'
      fullPath: '/system/tenants'
      preLoaderRoute: typeof SystemTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/': {
      id: '/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
  }
}

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorTestRoute: EditorTestRoute,
  SelectTenantRoute: SelectTenantRoute,
  SystemTenantsRoute: SystemTenantsRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
