/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace.$workspaceId'
import { Route as WorkspaceWorkspaceIdIndexRouteImport } from './routes/workspace.$workspaceId/index'
import { Route as WorkspaceWorkspaceIdVariablesRouteImport } from './routes/workspace.$workspaceId/variables'
import { Route as WorkspaceWorkspaceIdTemplatesRouteImport } from './routes/workspace.$workspaceId/templates'
import { Route as WorkspaceWorkspaceIdSettingsRouteImport } from './routes/workspace.$workspaceId/settings'
import { Route as WorkspaceWorkspaceIdDocumentsRouteImport } from './routes/workspace.$workspaceId/documents'
import { Route as WorkspaceWorkspaceIdAdministrationRouteImport } from './routes/workspace.$workspaceId/administration'
import { Route as WorkspaceWorkspaceIdTemplatesIndexRouteImport } from './routes/workspace.$workspaceId/templates.index'
import { Route as WorkspaceWorkspaceIdTemplatesTemplateIdRouteImport } from './routes/workspace.$workspaceId/templates.$templateId'
import { Route as WorkspaceWorkspaceIdEditorVersionIdRouteImport } from './routes/workspace.$workspaceId/editor.$versionId'
import { Route as WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRouteImport } from './routes/workspace.$workspaceId/editor.$templateId.version.$versionId'

const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdVariablesRoute =
  WorkspaceWorkspaceIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdTemplatesRoute =
  WorkspaceWorkspaceIdTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdSettingsRoute =
  WorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdDocumentsRoute =
  WorkspaceWorkspaceIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdAdministrationRoute =
  WorkspaceWorkspaceIdAdministrationRouteImport.update({
    id: '/administration',
    path: '/administration',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdTemplatesIndexRoute =
  WorkspaceWorkspaceIdTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceIdTemplatesRoute,
  } as any)
const WorkspaceWorkspaceIdTemplatesTemplateIdRoute =
  WorkspaceWorkspaceIdTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => WorkspaceWorkspaceIdTemplatesRoute,
  } as any)
const WorkspaceWorkspaceIdEditorVersionIdRoute =
  WorkspaceWorkspaceIdEditorVersionIdRouteImport.update({
    id: '/editor/$versionId',
    path: '/editor/$versionId',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute =
  WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRouteImport.update({
    id: '/editor/$templateId/version/$versionId',
    path: '/editor/$templateId/version/$versionId',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/administration': typeof WorkspaceWorkspaceIdAdministrationRoute
  '/workspace/$workspaceId/documents': typeof WorkspaceWorkspaceIdDocumentsRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/templates': typeof WorkspaceWorkspaceIdTemplatesRouteWithChildren
  '/workspace/$workspaceId/variables': typeof WorkspaceWorkspaceIdVariablesRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/editor/$versionId': typeof WorkspaceWorkspaceIdEditorVersionIdRoute
  '/workspace/$workspaceId/templates/$templateId': typeof WorkspaceWorkspaceIdTemplatesTemplateIdRoute
  '/workspace/$workspaceId/templates/': typeof WorkspaceWorkspaceIdTemplatesIndexRoute
  '/workspace/$workspaceId/editor/$templateId/version/$versionId': typeof WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/workspace/$workspaceId/administration': typeof WorkspaceWorkspaceIdAdministrationRoute
  '/workspace/$workspaceId/documents': typeof WorkspaceWorkspaceIdDocumentsRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/variables': typeof WorkspaceWorkspaceIdVariablesRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/editor/$versionId': typeof WorkspaceWorkspaceIdEditorVersionIdRoute
  '/workspace/$workspaceId/templates/$templateId': typeof WorkspaceWorkspaceIdTemplatesTemplateIdRoute
  '/workspace/$workspaceId/templates': typeof WorkspaceWorkspaceIdTemplatesIndexRoute
  '/workspace/$workspaceId/editor/$templateId/version/$versionId': typeof WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/administration': typeof WorkspaceWorkspaceIdAdministrationRoute
  '/workspace/$workspaceId/documents': typeof WorkspaceWorkspaceIdDocumentsRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/templates': typeof WorkspaceWorkspaceIdTemplatesRouteWithChildren
  '/workspace/$workspaceId/variables': typeof WorkspaceWorkspaceIdVariablesRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/editor/$versionId': typeof WorkspaceWorkspaceIdEditorVersionIdRoute
  '/workspace/$workspaceId/templates/$templateId': typeof WorkspaceWorkspaceIdTemplatesTemplateIdRoute
  '/workspace/$workspaceId/templates/': typeof WorkspaceWorkspaceIdTemplatesIndexRoute
  '/workspace/$workspaceId/editor/$templateId/version/$versionId': typeof WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/select-tenant'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/administration'
    | '/workspace/$workspaceId/documents'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/templates'
    | '/workspace/$workspaceId/variables'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/editor/$versionId'
    | '/workspace/$workspaceId/templates/$templateId'
    | '/workspace/$workspaceId/templates/'
    | '/workspace/$workspaceId/editor/$templateId/version/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/select-tenant'
    | '/workspace/$workspaceId/administration'
    | '/workspace/$workspaceId/documents'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/variables'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/editor/$versionId'
    | '/workspace/$workspaceId/templates/$templateId'
    | '/workspace/$workspaceId/templates'
    | '/workspace/$workspaceId/editor/$templateId/version/$versionId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/select-tenant'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/administration'
    | '/workspace/$workspaceId/documents'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/templates'
    | '/workspace/$workspaceId/variables'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/editor/$versionId'
    | '/workspace/$workspaceId/templates/$templateId'
    | '/workspace/$workspaceId/templates/'
    | '/workspace/$workspaceId/editor/$templateId/version/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SelectTenantRoute: typeof SelectTenantRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId/': {
      id: '/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/variables': {
      id: '/workspace/$workspaceId/variables'
      path: '/variables'
      fullPath: '/workspace/$workspaceId/variables'
      preLoaderRoute: typeof WorkspaceWorkspaceIdVariablesRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/templates': {
      id: '/workspace/$workspaceId/templates'
      path: '/templates'
      fullPath: '/workspace/$workspaceId/templates'
      preLoaderRoute: typeof WorkspaceWorkspaceIdTemplatesRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/settings': {
      id: '/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/documents': {
      id: '/workspace/$workspaceId/documents'
      path: '/documents'
      fullPath: '/workspace/$workspaceId/documents'
      preLoaderRoute: typeof WorkspaceWorkspaceIdDocumentsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/administration': {
      id: '/workspace/$workspaceId/administration'
      path: '/administration'
      fullPath: '/workspace/$workspaceId/administration'
      preLoaderRoute: typeof WorkspaceWorkspaceIdAdministrationRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/templates/': {
      id: '/workspace/$workspaceId/templates/'
      path: '/'
      fullPath: '/workspace/$workspaceId/templates/'
      preLoaderRoute: typeof WorkspaceWorkspaceIdTemplatesIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdTemplatesRoute
    }
    '/workspace/$workspaceId/templates/$templateId': {
      id: '/workspace/$workspaceId/templates/$templateId'
      path: '/$templateId'
      fullPath: '/workspace/$workspaceId/templates/$templateId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdTemplatesTemplateIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdTemplatesRoute
    }
    '/workspace/$workspaceId/editor/$versionId': {
      id: '/workspace/$workspaceId/editor/$versionId'
      path: '/editor/$versionId'
      fullPath: '/workspace/$workspaceId/editor/$versionId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdEditorVersionIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/editor/$templateId/version/$versionId': {
      id: '/workspace/$workspaceId/editor/$templateId/version/$versionId'
      path: '/editor/$templateId/version/$versionId'
      fullPath: '/workspace/$workspaceId/editor/$templateId/version/$versionId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
  }
}

interface WorkspaceWorkspaceIdTemplatesRouteChildren {
  WorkspaceWorkspaceIdTemplatesTemplateIdRoute: typeof WorkspaceWorkspaceIdTemplatesTemplateIdRoute
  WorkspaceWorkspaceIdTemplatesIndexRoute: typeof WorkspaceWorkspaceIdTemplatesIndexRoute
}

const WorkspaceWorkspaceIdTemplatesRouteChildren: WorkspaceWorkspaceIdTemplatesRouteChildren =
  {
    WorkspaceWorkspaceIdTemplatesTemplateIdRoute:
      WorkspaceWorkspaceIdTemplatesTemplateIdRoute,
    WorkspaceWorkspaceIdTemplatesIndexRoute:
      WorkspaceWorkspaceIdTemplatesIndexRoute,
  }

const WorkspaceWorkspaceIdTemplatesRouteWithChildren =
  WorkspaceWorkspaceIdTemplatesRoute._addFileChildren(
    WorkspaceWorkspaceIdTemplatesRouteChildren,
  )

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdAdministrationRoute: typeof WorkspaceWorkspaceIdAdministrationRoute
  WorkspaceWorkspaceIdDocumentsRoute: typeof WorkspaceWorkspaceIdDocumentsRoute
  WorkspaceWorkspaceIdSettingsRoute: typeof WorkspaceWorkspaceIdSettingsRoute
  WorkspaceWorkspaceIdTemplatesRoute: typeof WorkspaceWorkspaceIdTemplatesRouteWithChildren
  WorkspaceWorkspaceIdVariablesRoute: typeof WorkspaceWorkspaceIdVariablesRoute
  WorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceIdEditorVersionIdRoute: typeof WorkspaceWorkspaceIdEditorVersionIdRoute
  WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute: typeof WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdAdministrationRoute:
    WorkspaceWorkspaceIdAdministrationRoute,
  WorkspaceWorkspaceIdDocumentsRoute: WorkspaceWorkspaceIdDocumentsRoute,
  WorkspaceWorkspaceIdSettingsRoute: WorkspaceWorkspaceIdSettingsRoute,
  WorkspaceWorkspaceIdTemplatesRoute:
    WorkspaceWorkspaceIdTemplatesRouteWithChildren,
  WorkspaceWorkspaceIdVariablesRoute: WorkspaceWorkspaceIdVariablesRoute,
  WorkspaceWorkspaceIdIndexRoute: WorkspaceWorkspaceIdIndexRoute,
  WorkspaceWorkspaceIdEditorVersionIdRoute:
    WorkspaceWorkspaceIdEditorVersionIdRoute,
  WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute:
    WorkspaceWorkspaceIdEditorTemplateIdVersionVersionIdRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SelectTenantRoute: SelectTenantRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
