/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorTestRouteImport } from './routes/editor-test'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AppSelectTenantRouteImport } from './routes/_app/select-tenant'
import { Route as AppWorkspaceWorkspaceIdRouteImport } from './routes/_app/workspace/$workspaceId'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './routes/_app/workspace/$workspaceId/index'
import { Route as AppWorkspaceWorkspaceIdTemplatesRouteImport } from './routes/_app/workspace/$workspaceId/templates'
import { Route as AppWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_app/workspace/$workspaceId/settings'
import { Route as AppWorkspaceWorkspaceIdDocumentsRouteImport } from './routes/_app/workspace/$workspaceId/documents'

const EditorTestRoute = EditorTestRouteImport.update({
  id: '/editor-test',
  path: '/editor-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppSelectTenantRoute = AppSelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdTemplatesRoute =
  AppWorkspaceWorkspaceIdTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdSettingsRoute =
  AppWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdDocumentsRoute =
  AppWorkspaceWorkspaceIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/editor-test': typeof EditorTestRoute
  '/select-tenant': typeof AppSelectTenantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/workspace/$workspaceId/documents': typeof AppWorkspaceWorkspaceIdDocumentsRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/templates': typeof AppWorkspaceWorkspaceIdTemplatesRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/editor-test': typeof EditorTestRoute
  '/select-tenant': typeof AppSelectTenantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/workspace/$workspaceId/documents': typeof AppWorkspaceWorkspaceIdDocumentsRoute
  '/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/templates': typeof AppWorkspaceWorkspaceIdTemplatesRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/editor-test': typeof EditorTestRoute
  '/_app/select-tenant': typeof AppSelectTenantRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/_app/workspace/$workspaceId/documents': typeof AppWorkspaceWorkspaceIdDocumentsRoute
  '/_app/workspace/$workspaceId/settings': typeof AppWorkspaceWorkspaceIdSettingsRoute
  '/_app/workspace/$workspaceId/templates': typeof AppWorkspaceWorkspaceIdTemplatesRoute
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/editor-test'
    | '/select-tenant'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/'
    | '/admin/'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/documents'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/templates'
    | '/workspace/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/editor-test'
    | '/select-tenant'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/workspace/$workspaceId/documents'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/templates'
    | '/workspace/$workspaceId'
  id:
    | '__root__'
    | '/admin'
    | '/_app'
    | '/editor-test'
    | '/_app/select-tenant'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/tenants'
    | '/admin/users'
    | '/_app/'
    | '/admin/'
    | '/_app/workspace/$workspaceId'
    | '/_app/workspace/$workspaceId/documents'
    | '/_app/workspace/$workspaceId/settings'
    | '/_app/workspace/$workspaceId/templates'
    | '/_app/workspace/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  EditorTestRoute: typeof EditorTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor-test': {
      id: '/editor-test'
      path: '/editor-test'
      fullPath: '/editor-test'
      preLoaderRoute: typeof EditorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/select-tenant': {
      id: '/_app/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof AppSelectTenantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId': {
      id: '/_app/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/templates': {
      id: '/_app/workspace/$workspaceId/templates'
      path: '/templates'
      fullPath: '/workspace/$workspaceId/templates'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdTemplatesRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/settings': {
      id: '/_app/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/documents': {
      id: '/_app/workspace/$workspaceId/documents'
      path: '/documents'
      fullPath: '/workspace/$workspaceId/documents'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdDocumentsRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppWorkspaceWorkspaceIdRouteChildren {
  AppWorkspaceWorkspaceIdDocumentsRoute: typeof AppWorkspaceWorkspaceIdDocumentsRoute
  AppWorkspaceWorkspaceIdSettingsRoute: typeof AppWorkspaceWorkspaceIdSettingsRoute
  AppWorkspaceWorkspaceIdTemplatesRoute: typeof AppWorkspaceWorkspaceIdTemplatesRoute
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
}

const AppWorkspaceWorkspaceIdRouteChildren: AppWorkspaceWorkspaceIdRouteChildren =
  {
    AppWorkspaceWorkspaceIdDocumentsRoute:
      AppWorkspaceWorkspaceIdDocumentsRoute,
    AppWorkspaceWorkspaceIdSettingsRoute: AppWorkspaceWorkspaceIdSettingsRoute,
    AppWorkspaceWorkspaceIdTemplatesRoute:
      AppWorkspaceWorkspaceIdTemplatesRoute,
    AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
  }

const AppWorkspaceWorkspaceIdRouteWithChildren =
  AppWorkspaceWorkspaceIdRoute._addFileChildren(
    AppWorkspaceWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppSelectTenantRoute: typeof AppSelectTenantRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSelectTenantRoute: AppSelectTenantRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  EditorTestRoute: EditorTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
