# Doc Engine Configuration
# Override values using environment variables with prefix DOC_ENGINE_
# Example: DOC_ENGINE_SERVER_PORT=9000

environment: development

server:
  port: "8080"
  read_timeout: 30    # seconds
  write_timeout: 30   # seconds
  shutdown_timeout: 10 # seconds
  swagger_ui: false   # DOC_ENGINE_SERVER_SWAGGER_UI - Enable Swagger UI at /swagger/
  cors:
    allowed_origins: []  # Empty = allow all origins (*)
    # allowed_headers:       # Extra headers for CORS preflight (appended to built-in list)
    #   - X-Custom-Header

database:
  host: localhost             # Override via DOC_ENGINE_DATABASE_HOST
  port: 5432                  # Override via DOC_ENGINE_DATABASE_PORT
  user: postgres              # Override via DOC_ENGINE_DATABASE_USER
  password: ""                # Override via DOC_ENGINE_DATABASE_PASSWORD
  name: doc_assembly          # Override via DOC_ENGINE_DATABASE_NAME
  ssl_mode: disable           # Override via DOC_ENGINE_DATABASE_SSL_MODE
  max_pool_size: 10           # Override via DOC_ENGINE_DATABASE_MAX_POOL_SIZE_COUNT
  min_pool_size: 2            # Override via DOC_ENGINE_DATABASE_MIN_POOL_SIZE_COUNT
  max_idle_time_seconds: 300  # Override via DOC_ENGINE_DATABASE_MAX_IDLE_TIME_SECS

auth:
  dummy: false  # DOC_ENGINE_AUTH_DUMMY - Force dummy auth (bypass JWT). Use: make run DUMMY=1
  panel:
    name: keycloak
    discovery_url: ${DOC_ENGINE_AUTH_DISCOVERY_URL:}
    issuer: ${DOC_ENGINE_AUTH_ISSUER:}
    jwks_url: ${DOC_ENGINE_AUTH_JWKS_URL:}
    audience: ${DOC_ENGINE_AUTH_AUDIENCE:}
    client_id: ${DOC_ENGINE_AUTH_CLIENT_ID:}

# Internal API for service-to-service communication
internal_api:
  enabled: true
  api_key: ""    # DOC_ENGINE_INTERNAL_API_API_KEY - API key for internal service authentication

# Signing provider configuration (Documenso self-hosted)
signing:
  provider: documenso         # DOC_ENGINE_SIGNING_PROVIDER
  api_key: ""                 # DOC_ENGINE_SIGNING_API_KEY
  base_url: ""                # DOC_ENGINE_SIGNING_BASE_URL (default: https://app.documenso.com/api/v2)
  signing_base_url: ""        # DOC_ENGINE_SIGNING_SIGNING_BASE_URL (base URL for signing links, without /api/v2)
  webhook_secret: ""          # DOC_ENGINE_SIGNING_WEBHOOK_SECRET
  webhook_url: ""             # DOC_ENGINE_SIGNING_WEBHOOK_URL (public URL for receiving webhooks)

storage:
  provider: "local"            # DOC_ENGINE_STORAGE_PROVIDER - "s3" or "local"
  local_dir: "./data/storage"  # DOC_ENGINE_STORAGE_LOCAL_DIR - Base directory for local storage
  bucket: "contracts-bucket"
  region: "us-east-1"
  endpoint: ""  # For MinIO local development

logging:
  level: info   # debug, info, warn, error
  format: json  # json, text

# First-user bootstrap configuration
# When enabled, the first user to login via OIDC becomes SUPERADMIN automatically.
# This only happens when the database has zero users.
bootstrap:
  enabled: true  # DOC_ENGINE_BOOTSTRAP_ENABLED - Set false to require manual user setup

# Background scheduler configuration
scheduler:
  enabled: true
  polling_interval_sec: 60    # DOC_ENGINE_SCHEDULER_POLLING_INTERVAL_SEC
  polling_batch_size: 50      # DOC_ENGINE_SCHEDULER_POLLING_BATCH_SIZE
  expiration_days: 30         # DOC_ENGINE_SCHEDULER_EXPIRATION_DAYS - Days until document expires
  retry_max_retries: 5        # DOC_ENGINE_SCHEDULER_RETRY_MAX_RETRIES - Max retry attempts per document
  retry_batch_size: 20        # DOC_ENGINE_SCHEDULER_RETRY_BATCH_SIZE - Documents per retry cycle
  retry_interval_sec: 120     # DOC_ENGINE_SCHEDULER_RETRY_INTERVAL_SEC - Retry job interval

# Typst PDF renderer configuration
typst:
  bin_path: "typst"                      # DOC_ENGINE_TYPST_BIN_PATH - Path to the typst binary
  timeout_seconds: 30                    # DOC_ENGINE_TYPST_TIMEOUT_SECONDS - Max time per PDF compilation
  font_dirs: []                          # DOC_ENGINE_TYPST_FONT_DIRS - Additional font directories
  max_concurrent: 10                     # DOC_ENGINE_TYPST_MAX_CONCURRENT - Max simultaneous renders
  acquire_timeout_seconds: 5             # DOC_ENGINE_TYPST_ACQUIRE_TIMEOUT_SECONDS - Max wait for render slot
  template_cache_ttl_seconds: 60         # DOC_ENGINE_TYPST_TEMPLATE_CACHE_TTL_SECONDS - Template cache TTL
  template_cache_max_entries: 1000       # DOC_ENGINE_TYPST_TEMPLATE_CACHE_MAX_ENTRIES - Max cached templates
  image_cache_dir: ""                    # DOC_ENGINE_TYPST_IMAGE_CACHE_DIR - Image cache directory (empty = temp)
  image_cache_max_age_seconds: 300       # DOC_ENGINE_TYPST_IMAGE_CACHE_MAX_AGE_SECONDS - Cache TTL (5 min)
  image_cache_cleanup_interval_seconds: 60  # DOC_ENGINE_TYPST_IMAGE_CACHE_CLEANUP_INTERVAL_SECONDS

# Email notification configuration
notification:
  provider: "noop"   # DOC_ENGINE_NOTIFICATION_PROVIDER - "smtp" or "noop"
  from: ""           # DOC_ENGINE_NOTIFICATION_FROM - Sender email address
  host: ""           # DOC_ENGINE_NOTIFICATION_HOST - SMTP host (e.g. smtp.gmail.com)
  port: 587          # DOC_ENGINE_NOTIFICATION_PORT - SMTP port
  username: ""       # DOC_ENGINE_NOTIFICATION_USERNAME - SMTP username
  password: ""       # DOC_ENGINE_NOTIFICATION_PASSWORD - SMTP password or app password
