// Code generated by docengine-gen. DO NOT EDIT.
// Use 'make docengine-gen' to generate the registry.

package extensions

import (
	"github.com/doc-assembly/doc-engine/internal/core/port"
	"github.com/doc-assembly/doc-engine/internal/extensions/injectors"
	"github.com/doc-assembly/doc-engine/internal/extensions/injectors/datetime"
	"github.com/doc-assembly/doc-engine/internal/extensions/mappers"
)

// RegisterAll registers all discovered injectors and mappers.
// Note: i18n is automatically loaded from settings/injectors.i18n.yaml
func RegisterAll(injReg port.InjectorRegistry, mapReg port.MapperRegistry, deps *InitDeps) {
	// Global init (auto-discovered via //docengine:init)
	injReg.SetInitFunc(GlobalInit(deps))

	// Injectors (auto-discovered via //docengine:injector)
	injReg.Register(&datetime.DateNowInjector{})
	injReg.Register(&datetime.DateTimeNowInjector{})
	injReg.Register(&datetime.DayNowInjector{})
	injReg.Register(&datetime.MonthNowInjector{})
	injReg.Register(&datetime.TimeNowInjector{})
	injReg.Register(&datetime.YearNowInjector{})
	injReg.Register(&injectors.ExampleInjector{})
	injReg.Register(&injectors.ExampleTableInjector{})

	// Mapper (auto-discovered via //docengine:mapper)
	// Only ONE mapper is allowed - user handles routing internally
	mapReg.Set(&mappers.ExampleMapper{})
}
